OverlayFS support

diff --git a/initrd/initrd_create b/initrd/initrd_create
--- a/initrd/initrd_create
+++ b/initrd/initrd_create
@@ -27,7 +27,11 @@ rcopy()
    debug "rcopy $1 $2"
    CWD=$(pwd)
    if [ "$ROOT" = "" ]; then cd /; else cd $ROOT; fi
-   SOURCE="./${1:${#ROOT}}"
+   if [ -z "$1" ]; then
+       echo "rcopy: missing source argument"
+       return 1
+   fi
+   SOURCE="./${1:${#ROOT}}" # strips ROOT from SOURCE argument
    echo $SOURCE
    DEST="$2"
    if [ -L "$SOURCE" ]; then
@@ -108,7 +112,7 @@ done
 
 debug "copying files to the rootdisk"
 touch $INITRD_TREE/etc/{m,fs}tab
-cat liblinuxlive | sed -r 's/^LIVECDNAME=.*/LIVECDNAME="'$LIVECDNAME'"/' > $INITRD_TREE/liblinuxlive
+cat liblinuxlive >$INITRD_TREE/liblinuxlive
 cp {linuxrc,cleanup,cleandie} $INITRD_TREE
 chmod ago+x $INITRD_TREE/{linuxrc,cleanup,cleandie}
 
@@ -139,7 +143,24 @@ busybox_links "$INITRD_TREE"
 # necessary modules and dependency files
 mkdir -p $INITRD_TREE/$LMK/kernel/fs
 rcopy $ROOT/$LMK/kernel/fs/squashfs $INITRD_TREE
-rcopy $(find $ROOT/$LMK -name 'aufs.*') $INITRD_TREE
+if use_aufs; then
+    rcopy "$(aufs_modpath)" $INITRD_TREE
+    if [ "$?" -eq 0 ]; then
+	echo "found AUFS kernel module"
+    else
+	echo "missing AUFS kernel module"
+	exit 1
+    fi
+fi
+if use_overlay; then
+    rcopy "$(overlay_modpath)" $INITRD_TREE
+    if [ "$?" -eq 0 ]; then
+	echo "found OVERLAYFS kernel module"
+    else
+	echo "missing OVERLAYFS kernel module"
+	exit 1
+    fi
+fi
 
 # copy filesystem modules, if not directly copied into kernel
 rcopy_ex $ROOT/$LMK/kernel/lib/zlib_inflate $INITRD_TREE 2>>$DEBUG
diff --git a/initrd/linuxrc b/initrd/linuxrc
--- a/initrd/linuxrc
+++ b/initrd/linuxrc
@@ -17,7 +17,7 @@ header "starting Linux Live scripts <http://www.linux-live.org/>"
 # Syslog will reset printk settings, no need to remember it here anymore.
 echo "0" >/proc/sys/kernel/printk
 
-# Load essential drivers, like CDROM drivers, aufs/squashfs etc,
+# Load essential drivers, like CDROM drivers, aufs/overlay drivers, squashfs etc,
 # use mdev to create /dev/ devices and setup it as a hotplug-handler
 modprobe_essential_modules
 
@@ -131,7 +131,7 @@ if [ $? -ne 0 ]; then
    RAMSIZE=$(cmdline_value ramsize)
    if [ "$RAMSIZE" = "" ]; then RAMSIZE="60%"; fi
    mount -t tmpfs -o "size=$RAMSIZE" tmpfs $MEMORY
-   XINO=$MEMORY
+   XINO=$MEMORY # XINO = /memory
 else
    # So it is writable, we will keep the filesystem mounted.
    # Check if it supports links and chmod.
@@ -186,10 +186,14 @@ if [ "$XINO" != "$MEMORY" ]; then
 fi
 
 # mount aufs using the writable branch as the first one (leftmost/topmost)
-mount -t aufs -o nowarn_perm,xino=$XINO/.aufs.xino,br:$CHANGES=rw aufs $UNION
-if [ $? -ne 0 ]; then dmesg | tail -n 1; fatal "can't setup union (aufs)"; fi
-
-debug_shell
+# XINO = /memory
+# CHANGES = /memory/changes
+# UNION = /union
+if use_aufs; then
+    mount -t aufs -o nowarn_perm,xino=$XINO/.aufs.xino,br:$CHANGES=rw aufs $UNION
+    if [ $? -ne 0 ]; then dmesg | tail -n 1; fatal "can't setup union (aufs)"; fi
+    debug_shell
+fi
 
 # If toram or copy2ram boot parameter is present, copy all fs modules to RAM.
 # (skip modules from /optional/ which are not listed in load= boot option)
@@ -212,6 +216,10 @@ fi
 
 debug_shell
 
+# If not "use_aufs" is true, union will not contain mounted branches.
+# UNION = /union
+# IMAGES = /memory/images
+
 # DATA contains path to the base directory of all fs modules which need
 # to be mounted and inserted into live filesystem. Do it now.
 echolog "inserting all modules and creating live filesystem"
@@ -224,6 +232,15 @@ union_insert_modules $UNION $MEMORY $IMAGES
 # LIVECFG contains path to the base directory of config modules which need
 # to be mounted and inserted into live filesystem. Do it now.
 union_insert_modules $UNION $LIVECFG $IMAGES
+
+if use_overlay; then
+    LOWERDIRS="$(lowdirs_echo $UNION)"
+    echolog "Overlay branches: $LOWERDIRS"
+    mkdir "$XINO/work"
+    mount -t overlay overlay -olowerdir="$LOWERDIRS",upperdir="$CHANGES",workdir="$XINO/work" "$UNION"
+    if [ $? -ne 0 ]; then dmesg | tail -n 1; fatal "can't setup union (overlayfs)"; fi
+    debug_shell
+fi
 
 debug_shell
 
