Added initramfs support
The mod is still very alpha and untested

diff --git a/initrd/initrd_create b/initrd/initrd_create
--- a/initrd/initrd_create
+++ b/initrd/initrd_create
@@ -129,9 +129,15 @@ fi
 
 cp -a rootfs/* $INITRD_TREE
 
+if [ "$USEINITRAMFS" = "yes" ]; then
+    cp rootfs/bin/init $INITRD_TREE/init
+fi
+
 # build links to busybox's functions from busybox's own help text
 for i in $(rootfs/bin/busybox --help | grep -v Copyright | grep , | tr , " "); do
-   ln -s busybox $INITRD_TREE/bin/$i
+    if ! [ -a $INITRD_TREE/bin/$i ]; then
+	ln -s busybox $INITRD_TREE/bin/$i
+    fi
 done
 
 ln -sf bin $INITRD_TREE/sbin
@@ -205,44 +211,49 @@ mksquashfs $INITRD_TREE/$LMK/kernel/drivers $INITRD_TREE/drivers.lzm >/dev/null 
 chmod ago-x $INITRD_TREE/drivers.lzm
 rm -Rf $INITRD_TREE/$LMK/kernel/drivers/*
 
-debug "creating empty image file for initrd"
-dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >>$DEBUG 2>&1
+if [ "$USEINITRAMFS" = "yes" ]; then
+    debug "creating initramfs image"
+    mkinitramfs $INITRD_TREE $INITRDIMG.gz
+else
+    debug "creating empty image file for initrd"
+    dd if=/dev/zero of=$INITRDIMG bs=1024 count=$RAM0SIZE >>$DEBUG 2>&1
 
-debug "making filesystem"
-mkfs -t ext2 -F -m 0 -b 1024 -i 1024 $INITRDIMG >>$DEBUG 2>&1
-tune2fs -i 120m $INITRDIMG >>$DEBUG 2>&1
+    debug "making filesystem"
+    mkfs -t ext2 -F -m 0 -b 1024 -i 1024 $INITRDIMG >>$DEBUG 2>&1
+    tune2fs -i 120m $INITRDIMG >>$DEBUG 2>&1
 
-debug "creating empty directory $MOUNTDIR"
-rm -Rf $MOUNTDIR
-mkdir $MOUNTDIR
+    debug "creating empty directory $MOUNTDIR"
+    rm -Rf $MOUNTDIR
+    mkdir $MOUNTDIR
 
-debug "mounting $INITRDIMG to it"
-modprobe loop 2>>$DEBUG
-mount -o loop -t ext2 $INITRDIMG $MOUNTDIR
-if [ "$?" -ne 0 ]; then
-   echo "Error mounting initrd! Not enough free loop devices?"
-   exit 1
+    debug "mounting $INITRDIMG to it"
+    modprobe loop 2>>$DEBUG
+    mount -o loop -t ext2 $INITRDIMG $MOUNTDIR
+    if [ "$?" -ne 0 ]; then
+	echo "Error mounting initrd! Not enough free loop devices?"
+	exit 1
+    fi
+
+    debug "copying content of $INITRD_TREE to $MOUNTDIR"
+    rmdir $MOUNTDIR/lost+found
+    cp -R --preserve $INITRD_TREE/* $MOUNTDIR 2>/dev/null
+    if [ $? -ne 0 ]; then
+	debug "error copying data to mounted initrd. Increase RAM0SIZE"
+	echo "Not enough free space in initrd. Edit .config and increase RAM0SIZE !"
+	umount $MOUNTDIR
+	rm $INITRDIMG
+	exit 1
+    fi
+
+    debug "unmounting $MOUNTDIR"
+    umount $MOUNTDIR
+
+    debug "gzipping $INITRDIMG"
+    gzip --best $INITRDIMG
+
+    debug "deleting directory $MOUNTDIR"
+    rmdir $MOUNTDIR
 fi
-
-debug "copying content of $INITRD_TREE to $MOUNTDIR"
-rmdir $MOUNTDIR/lost+found
-cp -R --preserve $INITRD_TREE/* $MOUNTDIR 2>/dev/null
-if [ $? -ne 0 ]; then
-   debug "error copying data to mounted initrd. Increase RAM0SIZE"
-   echo "Not enough free space in initrd. Edit .config and increase RAM0SIZE !"
-   umount $MOUNTDIR
-   rm $INITRDIMG
-   exit 1
-fi
-
-debug "unmounting $MOUNTDIR"
-umount $MOUNTDIR
-
-debug "gzipping $INITRDIMG"
-gzip --best $INITRDIMG
-
-debug "deleting directory $MOUNTDIR"
-rmdir $MOUNTDIR
 
 debug "deleting directory $INITRD_TREE"
 rm -Rf $INITRD_TREE
diff --git a/initrd/linuxrc b/initrd/linuxrc
--- a/initrd/linuxrc
+++ b/initrd/linuxrc
@@ -6,8 +6,8 @@ export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin
 
 mount -n -t proc proc /proc
 mount -n -t sysfs sysfs /sys
-mount -n -o remount,rw /         # for the case we forgot rw boot option
-ln -sf /proc/mounts /etc/mtab    # this allows us to use umount -a
+mount -n -o remount,rw / 2>/dev/null  # for the case we forgot rw boot option
+ln -sf /proc/mounts /etc/mtab         # this allows us to use umount -a
 
 . liblinuxlive # it requires proc to be mounted
 
@@ -274,21 +274,26 @@ header "linux live end, starting $LIVECDNAME"
 
 debug_shell
 
+if [ $0 == "init" ]; then
+# We are in a initramfs
+    exec switch_root . /sbin/init
+else
+# We are in initrd
 # We will copy init from the distro to initrd (there should be 2MB free)
 # This allows us to use the cleanup script during reboot, as init will be
 # started from memory and not from the union and /union will not be busy.
-
-cp -af $INIT /bin
-if [ $? -eq 0 ]; then
-   pivot_root . $INITRAMDISK
-   cat $INITRAMDISK/proc/mounts >/etc/mtab
-   mount -n -o remount,ro /
-   exec $CHROOT . $INITRAMDISK/bin/init <dev/console >dev/console 2>&1
-else # If copying fails, start init directly.
-   pivot_root . $INITRAMDISK
-   cat $INITRAMDISK/proc/mounts >/etc/mtab
-   mount -n -o remount,ro /
-   exec $CHROOT . $INIT <dev/console >dev/console 2>&1
+    cp -af $INIT /bin
+    if [ $? -eq 0 ]; then
+	pivot_root . $INITRAMDISK
+	cat $INITRAMDISK/proc/mounts >/etc/mtab
+	mount -n -o remount,ro /
+	exec $CHROOT . $INITRAMDISK/bin/init <dev/console >dev/console 2>&1
+    else # If copying fails, start init directly.
+	pivot_root . $INITRAMDISK
+	cat $INITRAMDISK/proc/mounts >/etc/mtab
+	mount -n -o remount,ro /
+	exec $CHROOT . $INIT <dev/console >dev/console 2>&1
+    fi
 fi
 
 header "!!ERROR!!"
